id: IADF4F9A5
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-7806
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 11:28:53.086480+00:00
last_modified: 2023-09-28 11:28:53.086488+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16160
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG16160
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་གྱི་དོན་འགྲེལ་རྒྱལ་ཚབ་དགོངས་པ་རབ་གསལ་བློ་གསལ་གྱི་མགུལ་རྒྱན།
  languages:
  - bo
  author: སེ་ར་རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9971382652940373
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG16181:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16181
      total_pages: 592
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16181.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9971382652940373
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
